services:
  - type: web
    name: sales-engine-backend
    runtime: node
    rootDir: backendZip
    buildCommand: npm install
    startCommand: node src/server.js
    envVars:
      - key: NODE_ENV
        value: production
